### ISSUE TITLE
[Need Help] Got: No valid compiled python file (invalid magic)

### ISSUE THREAD

**Issue by xvdy** [flosch/GoPy#3]
When I clone your repo and run it on osx 10.12.6, here is something wrong with me.
```
➜  src git:(master) ✗ go run cmd/gopy-main/main.go -filename /Users/xuetang/workspace/go/src/github.com/flosch/GoPy/src/cmd/gopy-main/testapps/a.py

GoPy 0.1 - (C) 2012 Florian Schlachter, Berlin

2018/07/09 10:19:14 [Settings filename=/Users/xuetang/workspace/go/src/github.com/flosch/GoPy/src/cmd/gopy-main/testapps/a.py]

2018/07/09 10:19:14 [97 61 49 10]
2018/07/09 10:19:14 Parsing...
2018/07/09 10:19:14 170999137
2018/07/09 10:19:14 No valid compiled python file (invalid magic)
exit status 1
```
my go version is `go version go1.10.3 darwin/amd64` and the content of a.py is:
```
➜  src git:(master) ✗ cat cmd/gopy-main/testapps/a.py
a=1
```
If you need more information, please connect me.

The code stoped because this assert:
```
// src/vm/vm.go
	if magic != 168686339 {
		log.Fatal("No valid compiled python file (invalid magic)")
	}
```

I searched on the internet but cant find more information about it.

**Comment by lorenzleutgeb** [comment]
GoPy [has a hardcoded check for Python 2.7](https://github.com/flosch/GoPy/blob/a860d3e664457f51e8bf58aa5629306f00100efd/src/vm/vm.go#L38). If  you convert that number there to hexadecimal you get `0xA0DF303`. From there you may search the internet for Python magic numbers together with their version. For example [the pycdc project interprets this as Python 2.7](https://github.com/zrax/pycdc/blob/104c3c0b4275fc4383837ee1f6b4cd71ba26482e/pyc_module.h#L22).

**Comment by xvdy** [comment]
Thank you very much for your advise,I misused py and pyc. The vm shoud read and excute pyc, I give it python source file by mistake.
